const c = (constructionMaterials, criticalMaterials) => ({ constructionMaterials, criticalMaterials });
export const technologies = [
    { id: "basicSolar", name: "Basic Solar Array", tier: "basic", pathway: "solar", stage: "capture", cost: c(1, 1), knowledgeRequired: 0, capacity: 2, maximumInput: 5, maximumOutput: 2, alwaysAvailable: true },
    { id: "advancedSolar", name: "Advanced Solar Array", tier: "advanced", pathway: "solar", stage: "capture", cost: c(2, 2), knowledgeRequired: 3, capacity: 5, maximumInput: 5, maximumOutput: 5, alwaysAvailable: false },
    { id: "basicWind", name: "Basic Wind Turbine", tier: "basic", pathway: "wind", stage: "capture", cost: c(2, 1), knowledgeRequired: 0, capacity: 2, maximumInput: 5, maximumOutput: 2, alwaysAvailable: true },
    { id: "advancedWind", name: "Advanced Wind Turbine", tier: "advanced", pathway: "wind", stage: "capture", cost: c(3, 2), knowledgeRequired: 3, capacity: 5, maximumInput: 5, maximumOutput: 5, alwaysAvailable: false },
    { id: "basicReservoir", name: "Basic Reservoir", tier: "basic", pathway: "hydro", stage: "storage", cost: c(2, 0), knowledgeRequired: 0, capacity: 5, maximumInput: 5, maximumOutput: 5, storage: { type: "reservoir", capacity: 5, recovery: { outputsByInput: [0, 1, 2, 3, 4, 5] }, acceptedPathways: ["hydro"] }, alwaysAvailable: true },
    { id: "advancedReservoir", name: "Advanced Reservoir", tier: "advanced", pathway: "hydro", stage: "storage", cost: c(3, 1), knowledgeRequired: 2, capacity: 8, maximumInput: 8, maximumOutput: 8, storage: { type: "reservoir", capacity: 8, recovery: { outputsByInput: [0, 1, 2, 3, 4, 5, 6, 7, 8] }, acceptedPathways: ["hydro"] }, alwaysAvailable: false },
    { id: "basicHydroTurbine", name: "Basic Hydro Turbine", tier: "basic", pathway: "hydro", stage: "transformation", cost: c(2, 1), knowledgeRequired: 1, capacity: 3, maximumInput: 3, maximumOutput: 3, conversion: { outputsByInput: [0, 1, 2, 3] }, alwaysAvailable: true },
    { id: "advancedHydroTurbine", name: "Advanced Hydro Turbine", tier: "advanced", pathway: "hydro", stage: "transformation", cost: c(3, 2), knowledgeRequired: 3, capacity: 5, maximumInput: 5, maximumOutput: 5, conversion: { outputsByInput: [0, 1, 2, 3, 4, 5] }, alwaysAvailable: false },
    { id: "managedForest", name: "Managed Forest", tier: "basic", pathway: "biomass", stage: "capture", cost: c(1, 0), knowledgeRequired: 0, capacity: 1, maximumInput: 0, maximumOutput: 0, alwaysAvailable: true, special: "managedForest" },
    { id: "basicBiomassPlant", name: "Basic Biomass Plant", tier: "basic", pathway: "biomass", stage: "transformation", cost: c(2, 0), knowledgeRequired: 0, capacity: 2, maximumInput: 1, maximumOutput: 2, fuel: { resource: "biomass", units: 1 }, loss: { category: "thermal", fixedPerOperation: 2 }, alwaysAvailable: true },
    { id: "advancedBiomassPlant", name: "Advanced Biomass Plant", tier: "advanced", pathway: "biomass", stage: "transformation", cost: c(3, 1), knowledgeRequired: 2, capacity: 3, maximumInput: 1, maximumOutput: 3, fuel: { resource: "biomass", units: 1 }, loss: { category: "thermal", fixedPerOperation: 2 }, alwaysAvailable: false },
    { id: "basicFossilPlant", name: "Basic Fossil Plant", tier: "basic", pathway: "fossil", stage: "transformation", cost: c(2, 0), knowledgeRequired: 0, capacity: 3, maximumInput: 1, maximumOutput: 3, fuel: { resource: "fossilFuel", units: 1 }, loss: { category: "thermal", fixedPerOperation: 2 }, alwaysAvailable: true },
    { id: "combinedCycle", name: "Advanced Combined-Cycle Plant", tier: "advanced", pathway: "fossil", stage: "transformation", cost: c(3, 2), knowledgeRequired: 3, capacity: 4, maximumInput: 1, maximumOutput: 4, fuel: { resource: "fossilFuel", units: 1 }, loss: { category: "thermal", fixedPerOperation: 1 }, alwaysAvailable: false },
    { id: "basicBattery", name: "Basic Battery", tier: "basic", pathway: "shared", stage: "storage", cost: c(1, 2), knowledgeRequired: 1, capacity: 5, maximumInput: 5, maximumOutput: 4, storage: { type: "battery", capacity: 5, recovery: { outputsByInput: [0, 1, 2, 3, 3, 4] }, acceptedPathways: ["solar", "wind", "hydro", "biomass", "fossil"] }, alwaysAvailable: true },
    { id: "advancedBattery", name: "Advanced Battery", tier: "advanced", pathway: "shared", stage: "storage", cost: c(2, 3), knowledgeRequired: 3, capacity: 7, maximumInput: 7, maximumOutput: 6, storage: { type: "battery", capacity: 7, recovery: { outputsByInput: [0, 1, 2, 3, 4, 5, 5, 6] }, acceptedPathways: ["solar", "wind", "hydro", "biomass", "fossil"] }, alwaysAvailable: false },
    { id: "basicGrid", name: "Basic Grid", tier: "basic", pathway: "shared", stage: "transport", cost: c(0, 0), knowledgeRequired: 0, capacity: 4, maximumInput: 4, maximumOutput: 4, starter: true, alwaysAvailable: true },
    { id: "gridUpgrade", name: "Grid Upgrade", tier: "basic", pathway: "shared", stage: "transport", cost: c(2, 1), knowledgeRequired: 1, capacity: 2, maximumInput: 2, maximumOutput: 2, alwaysAvailable: true, special: "gridUpgrade" },
    { id: "standardLighting", name: "Standard Lighting", tier: "basic", pathway: "shared", stage: "lighting", cost: c(0, 0), knowledgeRequired: 0, capacity: 4, maximumInput: 4, maximumOutput: 3, conversion: { outputsByInput: [0, 1, 2, 3, 3] }, loss: { category: "lighting", inputMinusOutput: true }, starter: true, alwaysAvailable: true },
    { id: "efficientLighting", name: "Efficient Lighting", tier: "advanced", pathway: "shared", stage: "efficiency", cost: c(1, 2), knowledgeRequired: 2, capacity: 4, maximumInput: 4, maximumOutput: 4, conversion: { outputsByInput: [0, 1, 2, 3, 4] }, loss: { category: "lighting", inputMinusOutput: true }, alwaysAvailable: false, special: "efficientLighting", copyLimit: 1 },
    { id: "researchCentre", name: "Research Centre", tier: "basic", pathway: "shared", stage: "research", cost: c(2, 1), knowledgeRequired: 1, capacity: 1, maximumInput: 0, maximumOutput: 0, alwaysAvailable: true, special: "researchCentre", copyLimit: 1 }
];
//# sourceMappingURL=technologies.js.map