const c = (constructionMaterials, criticalMaterials) => ({ constructionMaterials, criticalMaterials });
const reservoirRecovery = capacity => ({ outputsByInput: Array.from({ length: capacity + 1 }, (_, value) => value) });

export const technologies = [
    // SOLAR — modular PV → utility-scale integration → high-performance tracked systems
    { id: "basicSolar", name: "Basic Solar Array", tier: "basic", pathway: "solar", stage: "capture", cost: c(1, 1), knowledgeRequired: 1, capacity: 2, maximumInput: 5, maximumOutput: 2, alwaysAvailable: true, copyLimit: 1, knowledgeRationale: "Mature modular photovoltaic systems can be deployed at small scale with standard electrical and installation skills." },
    { id: "utilitySolar", name: "Utility Solar Farm", tier: "intermediate", pathway: "solar", stage: "capture", cost: c(2, 2), knowledgeRequired: 3, prerequisiteTechnologyId: "basicSolar", capacity: 4, maximumInput: 5, maximumOutput: 4, alwaysAvailable: true, copyLimit: 1, knowledgeRationale: "Large solar farms require specialised design, inverters, protection, forecasting, land planning and grid connection." },
    { id: "advancedSolar", name: "High-Efficiency Solar System", tier: "advanced", pathway: "solar", stage: "capture", cost: c(3, 2), knowledgeRequired: 5, prerequisiteTechnologyId: "utilitySolar", capacity: 5, maximumInput: 5, maximumOutput: 5, alwaysAvailable: true, special: "advancedSolarResilience", copyLimit: 1, knowledgeRationale: "High-performance modules, tracking, advanced power electronics and system optimisation demand deep technical and operational capability." },

    // WIND — accessible land-based wind → large onshore fleets → offshore wind systems
    { id: "basicWind", name: "Community Wind Turbine", tier: "basic", pathway: "wind", stage: "capture", cost: c(2, 1), knowledgeRequired: 1, capacity: 2, maximumInput: 5, maximumOutput: 2, alwaysAvailable: true, copyLimit: 1, knowledgeRationale: "A mature land-based turbine still requires basic siting, mechanical, electrical and safety capability." },
    { id: "onshoreWindFarm", name: "Onshore Wind Farm", tier: "intermediate", pathway: "wind", stage: "capture", cost: c(3, 2), knowledgeRequired: 3, prerequisiteTechnologyId: "basicWind", capacity: 4, maximumInput: 5, maximumOutput: 4, alwaysAvailable: true, copyLimit: 1, knowledgeRationale: "A multi-turbine wind farm requires specialist resource assessment, foundations, controls, maintenance planning and grid integration." },
    { id: "advancedWind", name: "Offshore Wind Farm", tier: "advanced", pathway: "wind", stage: "capture", cost: c(4, 2), knowledgeRequired: 5, prerequisiteTechnologyId: "onshoreWindFarm", capacity: 5, maximumInput: 5, maximumOutput: 5, alwaysAvailable: true, special: "advancedWindResilience", copyLimit: 1, knowledgeRationale: "Marine foundations, specialised vessels, export cables, remote maintenance and harsh operating conditions make offshore wind highly demanding." },

    // HYDRO — each card is an integrated water-storage and turbine system
    { id: "basicReservoir", name: "Small Hydro System", tier: "basic", pathway: "hydro", stage: "transformation", cost: c(2, 1), knowledgeRequired: 1, capacity: 2, maximumInput: 2, maximumOutput: 2, storage: { type: "reservoir", capacity: 3, recovery: reservoirRecovery(3), acceptedPathways: ["hydro"] }, alwaysAvailable: true, copyLimit: 1, knowledgeRationale: "Small hydropower is mature, but still needs water-control, turbine, electrical and safety knowledge." },
    { id: "advancedReservoir", name: "Reservoir Hydro System", tier: "intermediate", pathway: "hydro", stage: "transformation", cost: c(3, 1), knowledgeRequired: 3, prerequisiteTechnologyId: "basicReservoir", capacity: 4, maximumInput: 4, maximumOutput: 4, storage: { type: "reservoir", capacity: 6, recovery: reservoirRecovery(6), acceptedPathways: ["hydro"] }, alwaysAvailable: true, copyLimit: 1, knowledgeRationale: "Reservoir hydropower requires integrated civil engineering, hydrology, operating rules, dam safety and environmental management." },
    { id: "advancedHydroTurbine", name: "Flexible Hydro Storage System", tier: "advanced", pathway: "hydro", stage: "transformation", cost: c(3, 2), knowledgeRequired: 5, prerequisiteTechnologyId: "advancedReservoir", capacity: 5, maximumInput: 5, maximumOutput: 5, storage: { type: "reservoir", capacity: 8, recovery: reservoirRecovery(8), acceptedPathways: ["hydro"] }, alwaysAvailable: true, special: "advancedHydroFlexibility", copyLimit: 1, knowledgeRationale: "Advanced flexible hydro combines large storage, sophisticated controls, forecasting, grid services and complex water-system operation." },

    // BIOMASS — accessible managed fuel → efficient CHP → integrated biorefinery
    { id: "basicBiomassPlant", name: "Managed Biomass Plant", tier: "basic", pathway: "biomass", stage: "transformation", cost: c(2, 0), knowledgeRequired: 1, capacity: 2, maximumInput: 1, maximumOutput: 2, fuel: { resource: "biomass", units: 1 }, loss: { category: "thermal", fixedPerOperation: 2 }, biomassRegrowth: 1, appliedLearning: true, alwaysAvailable: true, copyLimit: 1, knowledgeRationale: "Direct biomass combustion and managed feedstock supply use established equipment and practices, although sustainable operation still needs planning." },
    { id: "advancedBiomassPlant", name: "Efficient Biomass CHP", tier: "intermediate", pathway: "biomass", stage: "transformation", cost: c(3, 1), knowledgeRequired: 3, prerequisiteTechnologyId: "basicBiomassPlant", capacity: 3, maximumInput: 1, maximumOutput: 3, fuel: { resource: "biomass", units: 1 }, loss: { category: "thermal", fixedPerOperation: 1 }, biomassRegrowth: 1, appliedLearning: true, alwaysAvailable: true, copyLimit: 1, knowledgeRationale: "Combined heat and power needs better feedstock control, emissions treatment, heat recovery and coordinated operation." },
    { id: "integratedBiorefinery", name: "Integrated Biorefinery", tier: "advanced", pathway: "biomass", stage: "transformation", cost: c(3, 2), knowledgeRequired: 5, prerequisiteTechnologyId: "advancedBiomassPlant", capacity: 4, maximumInput: 1, maximumOutput: 4, fuel: { resource: "biomass", units: 1 }, loss: { category: "thermal", fixedPerOperation: 1 }, biomassRegrowth: 1, appliedLearning: true, alwaysAvailable: true, copyLimit: 1, knowledgeRationale: "Integrated biorefineries combine feedstock preparation, multiple conversion processes, product recovery, controls and complex supply-chain management." },

    // FOSSIL — available bridge → efficient combined cycle → complex capture-equipped plant
    { id: "basicFossilPlant", name: "Legacy Fuel Plant", tier: "basic", pathway: "fossil", stage: "transformation", cost: c(0, 0), knowledgeRequired: 1, capacity: 2, maximumInput: 1, maximumOutput: 2, fuel: { resource: "fossilFuel", units: 1 }, loss: { category: "thermal", fixedPerOperation: 2 }, starter: true, copyLimit: 1, alwaysAvailable: true, special: "legacyFuelBridge", knowledgeRationale: "Conventional thermal generation is established, although trained operation, maintenance and safety remain essential." },
    { id: "combinedCycle", name: "Combined-Cycle Plant", tier: "intermediate", pathway: "fossil", stage: "transformation", cost: c(3, 2), knowledgeRequired: 3, prerequisiteTechnologyId: "basicFossilPlant", capacity: 3, maximumInput: 1, maximumOutput: 3, fuel: { resource: "fossilFuel", units: 1 }, loss: { category: "thermal", fixedPerOperation: 1 }, copyLimit: 1, alwaysAvailable: true, special: "efficientFuelBridge", knowledgeRationale: "Combined-cycle plants integrate gas turbines, heat-recovery steam systems, controls and skilled maintenance." },
    { id: "carbonCapturePlant", name: "Fuel Plant with Carbon Capture", tier: "advanced", pathway: "fossil", stage: "transformation", cost: c(4, 2), knowledgeRequired: 5, prerequisiteTechnologyId: "combinedCycle", capacity: 4, maximumInput: 1, maximumOutput: 4, fuel: { resource: "fossilFuel", units: 1 }, loss: { category: "thermal", fixedPerOperation: 1 }, copyLimit: 1, alwaysAvailable: true, special: "advancedFuelBridge", knowledgeRationale: "Capture, compression, transport and storage systems add major process integration, monitoring and infrastructure requirements." },

    // SHARED STORAGE — also follows the 1 / 3 / 5 ladder
    { id: "basicBattery", name: "Basic Battery", tier: "basic", pathway: "shared", stage: "storage", cost: c(1, 2), knowledgeRequired: 1, capacity: 5, maximumInput: 5, maximumOutput: 4, storage: { type: "battery", capacity: 5, recovery: { outputsByInput: [0, 1, 2, 3, 3, 4] }, acceptedPathways: ["solar", "wind", "hydro", "biomass", "fossil"] }, alwaysAvailable: true, copyLimit: 1, knowledgeRationale: "Commercial battery systems are mature, but safe installation still requires power electronics and basic controls." },
    { id: "gridBattery", name: "Grid Battery", tier: "intermediate", pathway: "shared", stage: "storage", cost: c(2, 2), knowledgeRequired: 3, prerequisiteTechnologyId: "basicBattery", capacity: 6, maximumInput: 6, maximumOutput: 5, storage: { type: "battery", capacity: 6, recovery: { outputsByInput: [0, 1, 2, 3, 4, 4, 5] }, acceptedPathways: ["solar", "wind", "hydro", "biomass", "fossil"] }, alwaysAvailable: true, copyLimit: 1, knowledgeRationale: "Grid batteries require larger power-conversion systems, protection, thermal management and coordinated dispatch." },
    { id: "advancedBattery", name: "Long-Duration Storage", tier: "advanced", pathway: "shared", stage: "storage", cost: c(3, 2), knowledgeRequired: 5, prerequisiteTechnologyId: "gridBattery", capacity: 8, maximumInput: 8, maximumOutput: 7, storage: { type: "battery", capacity: 8, recovery: { outputsByInput: [0, 1, 2, 3, 4, 5, 5, 6, 7] }, acceptedPathways: ["solar", "wind", "hydro", "biomass", "fossil"] }, alwaysAvailable: true, copyLimit: 1, knowledgeRationale: "Long-duration storage remains less widely deployed and requires advanced system design, controls, safety validation and grid integration." },

    // SHARED TRANSPORT
    { id: "basicGrid", name: "Basic Grid", tier: "basic", pathway: "shared", stage: "transport", cost: c(0, 0), knowledgeRequired: 1, capacity: 4, maximumInput: 4, maximumOutput: 4, starter: true, alwaysAvailable: true, knowledgeRationale: "Basic electricity transport uses mature conductors, protection and operating practices." },
    { id: "gridUpgrade", name: "Grid Upgrade", tier: "intermediate", pathway: "shared", stage: "transport", cost: c(2, 1), knowledgeRequired: 3, prerequisiteTechnologyId: "basicGrid", capacity: 5, maximumInput: 5, maximumOutput: 5, alwaysAvailable: true, special: "gridUpgrade", copyLimit: 1, knowledgeRationale: "Higher-capacity grids require system studies, protection coordination and specialised construction while the network remains live." },
    { id: "smartGrid", name: "Smart Grid", tier: "advanced", pathway: "shared", stage: "transport", cost: c(3, 2), knowledgeRequired: 5, prerequisiteTechnologyId: "gridUpgrade", capacity: 6, maximumInput: 6, maximumOutput: 6, alwaysAvailable: true, special: "gridUpgrade", copyLimit: 1, knowledgeRationale: "Digital monitoring, advanced power-flow control, communications and cyber-secure operation require deep system-level capability." },

    // LIGHTING AND RESEARCH SUPPORT
    { id: "standardLighting", name: "Standard Lighting", tier: "basic", pathway: "shared", stage: "lighting", cost: c(0, 0), knowledgeRequired: 1, capacity: 4, maximumInput: 4, maximumOutput: 3, conversion: { outputsByInput: [0, 1, 2, 3, 3] }, loss: { category: "lighting", inputMinusOutput: true }, starter: true, alwaysAvailable: true, knowledgeRationale: "Conventional lighting is mature and straightforward to install and operate." },
    { id: "efficientLighting", name: "Efficient LED Lighting", tier: "intermediate", pathway: "shared", stage: "efficiency", cost: c(1, 2), knowledgeRequired: 3, prerequisiteTechnologyId: "standardLighting", capacity: 4, maximumInput: 4, maximumOutput: 4, conversion: { outputsByInput: [0, 1, 2, 3, 4] }, loss: { category: "lighting", inputMinusOutput: true }, alwaysAvailable: true, special: "efficientLighting", copyLimit: 1, knowledgeRationale: "LED systems are mature but good drivers, controls and system design require trained technical capability." },
    { id: "researchCentre", name: "Research Centre", tier: "intermediate", pathway: "shared", stage: "research", cost: c(2, 1), knowledgeRequired: 3, capacity: 1, maximumInput: 0, maximumOutput: 0, alwaysAvailable: true, special: "researchCentre", copyLimit: 1, knowledgeRationale: "A functioning research centre needs trained personnel, laboratories, institutions and sustained technical management." }
];
//# sourceMappingURL=technologies.js.map
